# Generated by Django 4.0.4 on 2022-05-10 13:55

from django.db import migrations, models
import materiais.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiais',
            name='id',
        ),
        migrations.AddField(
            model_name='materiais',
            name='id_material',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='materiais',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=materiais.models.upload_image),
        ),
    ]
